"""add user info

Revision ID: 3d83618387aa
Revises: 72ce06cb9ed6
Create Date: 2025-11-04 14:38:52.365782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d83618387aa'
down_revision = '72ce06cb9ed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('height_cm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('activity_level', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('maintenance_calories', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('calorie_goal', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('goal_weight_kg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('weekly_weight_change_lbs', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('weekly_weight_change_lbs')
        batch_op.drop_column('goal_weight_kg')
        batch_op.drop_column('calorie_goal')
        batch_op.drop_column('maintenance_calories')
        batch_op.drop_column('activity_level')
        batch_op.drop_column('height_cm')
        batch_op.drop_column('age')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
