"""add food measurements

Revision ID: 72ce06cb9ed6
Revises: 7c652e5d535a
Create Date: 2025-10-26 19:36:23.255510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72ce06cb9ed6'
down_revision = '7c652e5d535a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_measure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.Column('measure_name', sa.String(length=50), nullable=True),
    sa.Column('grams', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grams_per_unit', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.drop_column('grams_per_unit')

    op.drop_table('food_measure')
    # ### end Alembic commands ###
