"""add unit

Revision ID: 7c652e5d535a
Revises: 9c0446742d02
Create Date: 2025-10-26 12:35:58.873726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c652e5d535a'
down_revision = '9c0446742d02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_food_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_food_log', schema=None) as batch_op:
        batch_op.drop_column('unit')

    # ### end Alembic commands ###
