"""exercise cache

Revision ID: bb8574fda196
Revises: d29698284b41
Create Date: 2025-11-04 20:27:11.264372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb8574fda196'
down_revision = 'd29698284b41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('force', sa.String(length=50), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('mechanic', sa.String(length=50), nullable=True),
    sa.Column('equipment', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('primary_muscles', sa.String(length=200), nullable=True),
    sa.Column('secondary_muscles', sa.String(length=200), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('image_main', sa.String(length=255), nullable=True),
    sa.Column('image_secondary', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id')
    )
    with op.batch_alter_table('exercise_catalog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_catalog_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercise_catalog_equipment'), ['equipment'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercise_catalog_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercise_catalog_primary_muscles'), ['primary_muscles'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_catalog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_catalog_primary_muscles'))
        batch_op.drop_index(batch_op.f('ix_exercise_catalog_name'))
        batch_op.drop_index(batch_op.f('ix_exercise_catalog_equipment'))
        batch_op.drop_index(batch_op.f('ix_exercise_catalog_category'))

    op.drop_table('exercise_catalog')
    # ### end Alembic commands ###
