"""update for exercises

Revision ID: d29698284b41
Revises: bfb4f8dc304f
Create Date: 2025-11-04 19:33:53.184424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd29698284b41'
down_revision = 'bfb4f8dc304f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_session', schema=None) as batch_op:
        batch_op.drop_column('summary')
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###
